(function($){var ajax_opts={is_finished:false,is_loading:false,};if(sohailms_filter.current_paged==undefined){sohailms_filter.current_paged=2;}else{sohailms_filter.current_paged=parseInt(sohailms_filter.current_paged);}
if(sohailms_filter.current_view==undefined){setTimeout(function(){if(jQuery('.berocket_lgv_widget a.berocket_lgv_set.selected').hasClass('berocket_lgv_button_grid')){sohailms_filter.current_view='berocket_lgv_grid';}else{sohailms_filter.current_view='berocket_lgv_list';}},600);}
window.SADS={priceFilter:[{label:'Up to $50',val:'1_50'},{label:'$50 to $100',val:'50_100'},{label:'$100 to $500',val:'100_500'},{label:'$500 to $2,500',val:'500_2500'},{label:'$2,500 & above',val:'2500'},],deleteURLParam:function(key){var paramss=new URLSearchParams(location.search)
paramss.delete(key)
history.replaceState(null,'','?'+paramss+location.hash);},appendURLParams:function(params){const url=new URL(window.location.href);url.searchParams.set('advanced_filtering','yes');for(var key in params){if(params.hasOwnProperty(key)){if(params[key]!=undefined){if(key=='includein'){continue;}
if(params[key].length>0){url.searchParams.set(key,params[key]);}else{url.searchParams.delete(key,params[key]);}}}}
window.history.replaceState(null,null,url);},currenURLParems:function(){var parts=window.location.href.split('?'),s=(parts[1]||'');return{href:window.location.href,path:parts[0].replace(/#.*$/,''),search:(s.length?'?'+s:'')};},init:function(){function sohailms_render_filter(data,type){var processed=[];var filter_input_counter=0;var curr_params=SADS.currenURLParems().search;if('team'==type||'manufacturer'==type||'grade'==type||'year'==type||'sport'==type||'player'==type){var holder='#advanced_filters #filter_'+type+' .inner';var mobileholder='#mobile_filters_popup_holder .single_mobile_filters_wrapper[data-type="'+type+'"] .single_mobile_filters_wrapper_body';var heading='#advanced_filters #filter_'+type+' .heading';jQuery(heading).text(type);jQuery(holder).html('');jQuery(mobileholder).html('');var islastindex=false;for(var i=0;i<data.length;i++){var inner_value=data[i];var term_id=inner_value.term_id;var name=inner_value.facet_display_value;islastindex==(i==(data.length-1))?true:false;if(processed.indexOf(term_id)<0){if(jQuery(holder+' label').length==8&&!islastindex){jQuery(holder).append('<a href="#" class="load_more_filters">See More</a>');jQuery(holder).append('<div class="for_later_filters">');}
var checked=(curr_params.indexOf(term_id)>-1)?'checked="checked"':'';var mobileclass='';if(curr_params.indexOf(term_id)>-1){mobileclass='active';}
var active='';if(sohailms_filter.search_q.length>0&&sohailms_filter.search_q.toLowerCase().indexOf(name.toLowerCase())>-1){checked='checked="checked"';active='class="active"';}
jQuery(holder).append('<label '+active+'><input '+checked+' value="'+term_id+'" type="checkbox" name="filter_'+type+'" />'+name+'<span class="checkmark"></span></label>');if('year'==type){filter_input_counter++;}
jQuery(mobileholder).append('<a class="'+mobileclass+'" href="#" data-value="'+term_id+'">'+name+'</a>');}
if(islastindex){jQuery('</div>');}
processed.push(term_id);}
if('year'==type){jQuery('#laoded_years_count').val(filter_input_counter);}
jQuery('#mobile_filters_footer a span').text(sohailms_filter.found_posts);}}
function sohailms_groupBy(xs,key){return xs.reduce(function(rv,x){(rv[x[key]]=rv[x[key]]||[]).push(x);return rv;},{});};function sohailms_render_filters(filters){var grouped_arr=sohailms_groupBy(filters,'facet_name');var ready_arr=Object.entries(grouped_arr);if(Array.isArray(ready_arr)){for(var i=0;i<ready_arr.length;i++){if(Array.isArray(ready_arr[i])){var inner_arr=ready_arr[i];var key='';var islastindex=false;for(var j=0;j<inner_arr.length;j++){if(typeof inner_arr[j]=='string'){var key=inner_arr[j];}else if(typeof inner_arr[j]=='object'){var value=inner_arr[j];sohailms_render_filter(value,key);}}}}
jQuery('#advanced_filters').removeClass('loading').addClass('initialized');}}
if(jQuery('#advanced_filters').length<1){return;}
jQuery.ajax({type:'POST',url:sohailms_filter.ajaxurl,data:{action:'sohailms_get_filters',ids:JSON.stringify(sohailms_filter.filtered_ids),type:'init',},beforeSend:function(){},success:function(res){res=JSON.parse(res);if(res.results){sohailms_render_filters(res.results);SADS.initPriceFilter();SADS.bindEvents();}}});},initMagnifier:function(imgID,zoom){var img,glass,w,h,bw;img=imgID;glass=document.createElement("DIV");glass.setAttribute("class","img-magnifier-glass");img.parentElement.insertBefore(glass,img);glass.style.backgroundImage="url('"+img.src+"')";glass.style.backgroundRepeat="no-repeat";glass.style.backgroundSize=(img.width*zoom)+"px "+(img.height*zoom)+"px";bw=3;w=glass.offsetWidth/2;h=glass.offsetHeight/2;glass.addEventListener("mousemove",moveMagnifier);img.addEventListener("mousemove",moveMagnifier);glass.addEventListener("touchmove",moveMagnifier);img.addEventListener("touchmove",moveMagnifier);function moveMagnifier(e){var pos,x,y;e.preventDefault();pos=getCursorPos(e);x=pos.x;y=pos.y;if(x>img.width-(w/zoom)){x=img.width-(w/zoom);}
if(x<w/zoom){x=w/zoom;}
if(y>img.height-(h/zoom)){y=img.height-(h/zoom);}
if(y<h/zoom){y=h/zoom;}
glass.style.left=(x-w)+"px";glass.style.top=(y-h)+"px";glass.style.backgroundPosition="-"+((x*zoom)-w+bw)+"px -"+((y*zoom)-h+bw)+"px";}
function getCursorPos(e){var a,x=0,y=0;e=e||window.event;a=img.getBoundingClientRect();x=e.pageX-a.left;y=e.pageY-a.top;x=x-window.pageXOffset;y=y-window.pageYOffset;return{x:x,y:y};}},initListView:function(){jQuery('#newlist_popup_closer').off().on('click',function(e){e.preventDefault();jQuery('body').removeClass('newlist_view_popupactive');jQuery('#newlist_view_popup').removeClass('loaded');jQuery('div#mag_zoom_btns button').removeClass('active');jQuery('div#mag_zoom_btns button:first-child').addClass('active');jQuery('input#toggle_zoom_glass').prop('checked',false).trigger('change');jQuery('div#mag_zoom_btns,.zomm_mag_msg').removeClass('loaded');jQuery('#popup_view_detailer').attr('href','#');jQuery('div#newlist_view_popup .inner').removeAttr('style');setTimeout(function(){jQuery('#newlist_view_popup').removeClass('horizontal');},800);});jQuery('body.newlist_view .products .berocket_lgv_grid .priceslog .newlinelog').on('click',function(){var _parent=jQuery(this).closest('.priceslog');_parent.find('.newlinelog').removeClass('active');jQuery(this).addClass('active');});jQuery('.newlist_popup_opener').off().on('click',function(e){e.preventDefault();var _width=parseInt(jQuery(this).attr('data-width'));var _height=parseInt(jQuery(this).attr('data-height'));if((_width>_height)&&(jQuery(window).width()>767)){jQuery('div#newlist_view_popup .inner').css({'min-width':'680px','max-width':'680px'});jQuery('#newlist_view_popup').addClass('horizontal');}
var _parent=jQuery(this).closest('.newlinelog');var _grand_parent=_parent.closest('.product-small');var _type=jQuery(this).attr('data-type');var _image=jQuery(this).attr('data-image');var _firstimage=_lastimage='';if(_type=='front'){_firstimage=_image;_lastimage=_parent.find('a[data-type="back"]').attr('data-image');}else if(_type=='back'){_firstimage=_image;_lastimage=_parent.find('a[data-type="front"]').attr('data-image');}
var _heading=_grand_parent.find('.title-wrapper h3').html();var _sub_heading=_grand_parent.find('.title-wrapper h4').html();var _var_name=_parent.find('.cgrade span').text();var _var_price=_parent.find('.cgrade').next('div').html();var _detail_link=jQuery(this).attr('data-popuplink');var _popup=jQuery('#newlist_view_popup');var _slider=jQuery('#newlist_view_popup_slider_holder');_slider.removeClass();_slider.html('').append('<div class="single_image"><img src="'+_firstimage+'" /></div>');_slider.append('<div class="single_image"><img src="'+_lastimage+'" /></div>');_popup.find('.header h2').html(_heading);_popup.find('.header .left_side').html(_sub_heading);_popup.find('.footer .meta .var_name_holder').text(_var_name);_popup.find('.footer .meta .var_price_holder').html(_var_price);jQuery('#popup_view_detailer').attr('href',_detail_link);jQuery('#newlist_view_addcart_btn').attr('data-var_id',_parent.find('.add_to_cart_button').attr('data-var_id'));if(_parent.hasClass('in_cart')){jQuery('#newlist_view_addcart_btn').text('In Cart');jQuery('#newlist_view_addcart_btn').addClass('added');}else{jQuery('#newlist_view_addcart_btn').text('Add To Cart');jQuery('#newlist_view_addcart_btn').removeClass('added');}
jQuery('body').addClass('newlist_view_popupactive');_slider.removeClass();_slider.trigger('destroy.owl.carousel');_slider.owlCarousel('destroy');_slider.find('img').on('load',function(){_slider.addClass("owl-carousel").owlCarousel({items:1,nav:true,loop:true,dots:false,mouseDrag:false,touchDrag:false});});_popup.addClass('loaded');setTimeout(function(){jQuery('input#toggle_zoom_glass').off().on('change',function(){var _is_checked=jQuery(this).prop('checked');if(_is_checked==true){jQuery('div#mag_zoom_btns button').removeClass('active');jQuery('div#mag_zoom_btns button:first-child').addClass('active');if(jQuery(window).width()<=767){jQuery('#newlist_view_popup_slider_holder .single_image img').parent().zoom({magnify:0.3});}else{jQuery('#newlist_view_popup_slider_holder .single_image').each(function(){var _image=jQuery(this).attr('src');jQuery(this).izoomify({url:_image,magnify:2});});}
jQuery('div#mag_zoom_btns,.zomm_mag_msg').addClass('loaded');}else{jQuery('#newlist_view_popup_slider_holder .single_image').each(function(){var _image=jQuery(this).attr('src');jQuery(this).trigger('izoomify.destroy');});jQuery('#newlist_view_popup_slider_holder .single_image img').trigger('zoom.destroy');jQuery('div#mag_zoom_btns,.zomm_mag_msg').removeClass('loaded');}});jQuery('div#mag_zoom_btns button').off().on('click',function(e){e.preventDefault();var _zoom=parseInt(jQuery(this).attr('data-zoom'));jQuery('div#mag_zoom_btns button').removeClass('active');jQuery(this).addClass('active');if(jQuery(window).width()<=767){jQuery('#newlist_view_popup_slider_holder .single_image img').trigger('zoom.destroy');var _zooms=_zoom/10;jQuery('#newlist_view_popup_slider_holder .single_image img').parent().zoom({magnify:_zooms});}else{jQuery('#newlist_view_popup_slider_holder .single_image').each(function(){var _image=jQuery(this).attr('src');jQuery(this).izoomify({url:_image,magnify:_zoom});});}});},1200);});jQuery('body.newlist_view .berocket_lgv_list .box-text-products .priceslog .newlinelog a.newlist_custom_addcart,body.newlist_view .berocket_lgv_grid .box-text-products .priceslog .newlinelog a.newlist_custom_addcart').off().on('click',function(e){e.preventDefault();var _btn=jQuery(this);if(_btn.hasClass('processing')){return;}
var _parent=jQuery(this).closest('.newlinelog');if(_btn.hasClass('added')){var _parent_id=_btn.next('.button').attr('data-parent_id');var _var_id=_btn.next('.button').attr('data-var_id');var _link=jQuery('li.woocommerce-mini-cart-item >  a[data-product_id="'+_parent_id+'"]');if(_link){_link.click();}
_btn.removeClass('added');_btn.removeClass('processing');_btn.text('Add To Cart');_parent.removeClass('in_cart');return;}
_btn.addClass('processing');_btn.next('.button').click();var id=setInterval(function(){if(_btn.next('.button').hasClass('added')){clearInterval(id);_btn.text('In Cart');_btn.addClass('added');_parent.addClass('in_cart');}},200);});jQuery('#newlist_view_addcart_btn').off().on('click',function(e){e.preventDefault();var _btn=jQuery(this);if(_btn.hasClass('processing')){return;}
var _var_id=_btn.attr('data-var_id');var _target_btn=jQuery('.newlinelog .add_to_cart_button[data-var_id="'+_var_id+'"]');if(_btn.hasClass('added')){_target_btn.prev('a').click();_btn.removeClass('added');_btn.text('Add To Cart');return;}
_btn.addClass('processing');_target_btn.prev('a').click();var id=setInterval(function(){if(_target_btn.hasClass('added')){clearInterval(id);_btn.text('In Cart');_btn.addClass('added');}},200);});jQuery('body.newlist_view .products .berocket_lgv_grid .priceslog .newlinelog').off().on('click',function(){var _parent=jQuery(this).closest('.priceslog');var _grand_parent=_parent.closest('.product-small');_parent.find('.newlinelog').removeClass('active');jQuery(this).addClass('active');var _fimage=jQuery(this).attr('data-fimage');var _bimage=jQuery(this).attr('data-bimage');var _slider=_grand_parent.find('.lightSlider');_slider.html('');_slider.append('<li><img src="'+_fimage+'" /></li>');_slider.append('<li><img src="'+_bimage+'" /></li>');_slider.trigger('destroy.owl.carousel');_slider.owlCarousel('destroy').removeClass('owl-carousel');_slider.addClass("owl-carousel").owlCarousel({items:1,nav:true,loop:true,dots:false,});});jQuery('#adv_filter_opener').off().on('click',function(e){e.preventDefault();var _btn=jQuery(this);if(jQuery(window).width()<767){jQuery('#mobile_filters_opener').click();return;}
_btn.toggleClass('active');jQuery('body').toggleClass('sidebar_filter_opened');});if(jQuery(window).width()<767){}
jQuery('.mobile_card_viewer').off().on('click',function(e){e.preventDefault();var _parent=jQuery(this).closest('.newlinelog');_parent.find('.cgrade + div + div a').trigger('click');});jQuery('.berocket_lgv_widget .right a').off().on('click',function(e){e.preventDefault();var _parent=jQuery(this).closest('.right');_parent.find('a').removeClass('selected');var _type=jQuery(this).attr('data-type');jQuery(this).addClass('selected');jQuery('body.newlist_view .products .product-small').removeClass('berocket_lgv_list');jQuery('body.newlist_view .products .product-small').removeClass('berocket_lgv_grid');if(_type=='list'){jQuery('body.newlist_view .products .product-small').addClass('berocket_lgv_list');sohailms_filter.current_view='berocket_lgv_list';}
if(_type=='grid'){jQuery('body.newlist_view .products .product-small').addClass('berocket_lgv_grid');sohailms_filter.current_view='berocket_lgv_grid';}
document.cookie="sohailms_defaultview="+encodeURIComponent(_type)+";path=/";});jQuery('span.left_side_results_holder .number').text(jQuery('.results_found').text());if(parseInt(jQuery('.results_found').text())<25){jQuery('.infinite_loading_wrapper').remove();console.log('removing infinite div');}
jQuery('a.more_var_loader').off().on('click',function(e){e.preventDefault();jQuery(this).closest('.priceslog').addClass('more_loaded');var _height=(30*jQuery(this).closest('.priceslog').find('.newlinelog').length)+75;jQuery('.box-text-products').each(function(){jQuery(this).attr('style','min-height:'+_height+'px;');});jQuery(this).remove();jQuery('body').addClass('increased_height');});if(jQuery('body').hasClass('tax-product_cat')){jQuery(window).on('scroll touchstart',function(){jQuery(this).trigger('infinite_scroll_start_tax');});jQuery('.infinite_loading_wrapper_tax a').off().on('click',function(e){e.preventDefault();});}
jQuery(window).on('infinite_scroll_start_tax',function(){var t=jQuery(this);var elem=jQuery('.infinite_loading_wrapper_tax');if(typeof elem=='undefined'||elem.length<1){return;}
if(!taxajaxopts.isloading&&currenttaxpage<=totaltaxpage&&(t.scrollTop()+t.height())>=(elem.offset().top-(2*elem.height()))){do_sohailms_ajax_tax();}});jQuery(window).on('scroll touchstart',function(){const url=window.location.search;const urlParams=new URLSearchParams(url);jQuery(this).trigger('infinite_scroll_start');});jQuery(window).on('infinite_scroll_start',function(){var t=jQuery(this);var elem=jQuery('.infinite_loading_wrapper');if(typeof elem=='undefined'||elem.length<1){return;}
if(!ajax_opts.is_loading&&sohailms_filter.current_paged<=sohailms_filter.total_pages&&(t.scrollTop()+t.height())>=(elem.offset().top-(2*elem.height()))){do_sohailms_ajax();}});function onlyUnique(value,index,self){return self.indexOf(value)===index;}
function do_sohailms_ajax_tax(){jQuery.ajax({url:sohailms_filter.ajaxurl,type:'POST',cache:false,data:{action:'sohailms_infinite_scroll_fetch_tax',query:taxfullquery,page:currenttaxpage,},beforeSend:function(){taxajaxopts.isloading=true;jQuery('.infinite_loading_wrapper_tax a').addClass('loading').text('Loading');},success:function(res){res=JSON.parse(res);taxajaxopts.isloading=false;window.currenttaxpage=currenttaxpage+1;if(res.content){jQuery('.row.category-page-row.ddadsd .tax_item_appender').append(res.content);jQuery('.infinite_loading_wrapper_tax a').removeClass('loading').text('Load More');}
if(currenttaxpage>=totaltaxpage){taxajaxopts.isloading=false;jQuery('.infinite_loading_wrapper_tax a').addClass('done').text('All Items Loaded!');}}});}
function do_sohailms_ajax(){if(jQuery('body').hasClass('page-id-1136951')&&sohailms_filter.current_paged>8){sohailms_filter.current_paged=10;sohailms_filter.total_pages=9;ajax_opts.is_loading=false;if(sohailms_filter.current_paged>=sohailms_filter.total_pages&&!ajax_opts.is_loading){jQuery('.infinite_loading_wrapper a').addClass('done').text('All Products Loaded!');}
return;}
window.testarr=[];jQuery('.product-small').each(function(){var _id=jQuery(this).attr('data-testid');if(_id==undefined||_id.length<1){return;}
window.testarr.push(_id);});window.testarr=window.testarr.filter(onlyUnique);var not_in=window.testarr.join(',');jQuery.ajax({url:sohailms_filter.ajaxurl,type:'POST',cache:false,data:{action:'sohailms_infinite_scroll_fetch',paged:sohailms_filter.current_paged,query:sohailms_filter.full_query,notin:not_in},beforeSend:function(){ajax_opts.is_loading=true;jQuery('.infinite_loading_wrapper a').addClass('loading');console.log(sohailms_filter.current_paged);},success:function(res){res=JSON.parse(res);if(res.content){if(sohailms_filter.current_view=='berocket_lgv_grid'){res.content=res.content.replaceAll('berocket_lgv_list','berocket_lgv_grid');}else if(sohailms_filter.current_view=='berocket_lgv_list'){res.content=res.content.replaceAll('berocket_lgv_grid','berocket_lgv_list');}
ajax_opts.is_loading=false;sohailms_filter.current_paged=sohailms_filter.current_paged+1;jQuery('.products.row').append(res.content);jQuery('.infinite_loading_wrapper a').removeClass('loading');setTimeout(function(){SADS.initLoopSlider()},300);if(sohailms_filter.current_paged>=sohailms_filter.total_pages&&!ajax_opts.is_loading){jQuery('.infinite_loading_wrapper a').addClass('done').text('All Products Loaded!');}
setTimeout(function(){SADS.initListView();},1000);setTimeout(function(){jQuery('.fornew_listview.newactions a.single_var_alert').off().on('click',function(e){e.preventDefault();var _this=jQuery(this);var _id=_this.attr('data-id');var _settings=JSON.parse(_this.attr('data-settings'));var _parent=_this.closest('.dsdadddd.product-small.box');var _settings=JSON.parse(_this.attr('data-settings'));if(_settings.item_unavailable_var&&_settings.item_unavailable_var=='active'){_parent.find('input[value="item_unavailable"]').prop('checked',true);}else{_parent.find('input[value="item_unavailable"]').prop('checked',false);}
if(_settings.item_available_var&&_settings.item_available_var=='active'){_parent.find('input[value="item_available"]').prop('checked',true);}else{_parent.find('input[value="item_available"]').prop('checked',false);}
_parent.find('.footer a.confirm').attr('data-id',_id);_parent.addClass('flipped listview');});jQuery('.new_design_alert,.alert_flipbox_inner .footer a.cancel').off().on('click',function(e){e.preventDefault();var _this=jQuery(this);var _parent=_this.closest('.alert_flipbox_wrapper');_parent.find('input[type="checkbox"]').each(function(){var _val=jQuery(this).attr('data-original_val');if(_val=='active'){jQuery(this).prop('checked',true);}else{jQuery(this).prop('checked',false);}});var _confirm=_this.prev('a.confirm');_confirm.attr('data-id',_confirm.attr('data-org_id'));jQuery(this).closest('.dsdadddd.product-small.box').toggleClass('flipped').removeClass('listview');});jQuery('body.logged-in .dsdadddd.product-small.box .alert_flipbox_wrapper .alert_flipbox_inner .footer a.confirm').off().on('click',function(e){e.preventDefault();var _this=jQuery(this);var _parent=_this.closest('.alert_flipbox_wrapper');var _id=parseInt(_this.attr('data-id'));var _variation_added=_parent.find('input[value="variation_added"]').is(':checked');var _variation_out_of_stock=_parent.find('input[value="variation_out_of_stock"]').is(':checked');var _price_change=_parent.find('input[value="price_change"]').is(':checked');var _item_unavailable=_parent.find('input[value="item_unavailable"]').is(':checked');var _item_available=_parent.find('input[value="item_available"]').is(':checked');var _data={variation_added:_variation_added,variation_out_of_stock:_variation_out_of_stock,price_change:_price_change,item_available:_item_available,item_unavailable:_item_unavailable,id:_id,action:'sohailms_set_notification_alert',};if(_parent.closest('.dsdadddd.product-small.box').hasClass('listview')){_data.ptype='variation';}
jQuery.ajax({url:sohailms_filter.ajaxurl,type:'POST',data:_data,beforeSend:function(){_parent.addClass('sending_data');},success:function(res){_parent.removeClass('sending_data');console.log(res);if(res.success&&res.data.saved_data){if(_parent.closest('.dsdadddd.product-small.box').hasClass('listview')){jQuery('a[data-id="'+_id+'"]').attr('data-settings',JSON.stringify(res.data.saved_data));if(res.data.saved_data.item_unavailable_var=='active'||res.data.saved_data.item_available_var=='active'){jQuery('a[data-id="'+_id+'"]').addClass('filled');}else{jQuery('a[data-id="'+_id+'"]').removeClass('filled');}}
_parent.find('input[value="price_change"]').attr('data-original_val',res.data.saved_data.price_change);_parent.find('input[value="variation_added"]').attr('data-original_val',res.data.saved_data.variation_added);_parent.find('input[value="variation_out_of_stock"]').attr('data-original_val',res.data.saved_data.variation_out_of_stock);if(res.data.saved_data.price_change=='active'||res.data.saved_data.variation_added=='active'||res.data.saved_data.variation_out_of_stock=='active'){_parent.closest('.product-small.col').find('.new_design_alert').addClass('filled');_parent.closest('.product-small.col').find('.alert_flipbox_wrapper h3 span:last-child').addClass('filled');}else{_parent.closest('.product-small.col').find('.new_design_alert').removeClass('filled');_parent.closest('.product-small.col').find('.alert_flipbox_wrapper h3 span:last-child').removeClass('filled');}
_parent.closest('.dsdadddd.product-small.box').removeClass('flipped');}}});});},2500);}}});}
if(jQuery(window).width()<768){if(jQuery('.subcategs').length<1){return;}
var _headerHeight=jQuery('#masthead').height();var _subOffTop=jQuery('.subcategs').offset()?.top;var _limit=_subOffTop-_headerHeight;jQuery(window).on('scroll',function(){if(jQuery(this).scrollTop()>_limit){jQuery('.subcategs').addClass('show_sticky');}else{jQuery('.subcategs').removeClass('show_sticky');}});}},fetchAndRenderFilters:function(){var manufacturer=jQuery('#advanced_filters #filter_manufacturer input[type="checkbox"]:checked');var team=jQuery('#advanced_filters #filter_team input[type="checkbox"]:checked');var price=jQuery('#advanced_filters #filter_price input[type="checkbox"]:checked').val();var grade=jQuery('#advanced_filters #filter_grade input[type="checkbox"]:checked');var year=jQuery('#advanced_filters #filter_year input[type="checkbox"]:checked');var sport=jQuery('#advanced_filters #filter_sport input[type="checkbox"]:checked');var player=jQuery('#advanced_filters #filter_player input[type="checkbox"]:checked');var is_single_year_page=jQuery('#is_single_year_page').val();var laoded_years_count=jQuery('#laoded_years_count').val();if(price==undefined){price='';}
var sortby=jQuery('#custom_product_sorter_sorter').val();if(sortby==undefined){sortby='';}
var manufacturers=teams=prices=grades=years=sports=players='';year.each(function(){years+=jQuery(this).val()+',';});years=years.replace(/,\s*$/,"");manufacturer.each(function(){manufacturers+=jQuery(this).val()+',';});manufacturers=manufacturers.replace(/,\s*$/,"");player.each(function(){players+=jQuery(this).val()+',';});players=players.replace(/,\s*$/,"");team.each(function(){teams+=jQuery(this).val()+',';});teams=teams.replace(/,\s*$/,"");sport.each(function(){sports+=jQuery(this).val()+',';});sports=sports.replace(/,\s*$/,"");grade.each(function(){grades+=jQuery(this).val()+',';});grades=grades.replace(/,\s*$/,"");if(jQuery('input[name="min_price"]').val().length>0&&jQuery('input[name="max_price"]').val().length>0){price=jQuery('input[name="min_price"]').val()+'_'+jQuery('input[name="max_price"]').val();}
var query={manufacturer:manufacturers,team:teams,price:price,grade:grades,year:years,sport:sports,player:players,is_single_year_page:is_single_year_page,laoded_years_count:laoded_years_count,sortby:sortby};if(manufacturers.length<1&&teams.length<1&&prices.length<1&&grades.length<1&&years.length<1){query.includein=JSON.stringify(sohailms_filter.filtered_ids);}else{query.includein=JSON.stringify(sohailms_filter.filtered_ids);}
SADS.appendURLParams(query);var query_args={posts_per_page:sohailms_filter.posts_per_page,paged:sohailms_filter.paged};jQuery.ajax({url:sohailms_filter.ajaxurl,type:'POST',data:{action:'sohailms_get_filtered_products',query:query,query_args:query_args,tax_query:sohailms_filter.tax_query},beforeSend:function(){jQuery('div#advanced_filters,.shop-container,#mobile_filters_popup_holder').addClass('loading');},success:function(res){jQuery('div#advanced_filters,.shop-container,#mobile_filters_popup_holder').removeClass('loading');res=JSON.parse(res);jQuery('.products.row').html('').html(res.content);SADS.initLoopSlider();jQuery('.sohailms_pagination:not(.ajaxed)').remove();SADS.bindEvents();var founded_posts=jQuery('#founded_posts');if(founded_posts&&founded_posts.length>0){jQuery('#mobile_filters_footer a span').text(founded_posts.text());}},error:function(){}});},bindEvents:function(){jQuery('#advanced_filters input[type="checkbox"],#advanced_filters input[type="radio"]').off().on('change',function(){var _filter=jQuery(this).closest('.advanced_filter').attr('data-filter');if(jQuery(this).prop('checked')){if(_filter=='price'){jQuery('#filter_price label').removeClass('active');jQuery(this).closest('.advanced_filter').find('label').removeClass('active');jQuery(this).closest('.advanced_filter').find('input').prop('checked',false);jQuery(this).prop('checked',true);}
jQuery(this).closest('label').addClass('active');}else{jQuery(this).closest('label').removeClass('active');}
if(_filter=='grade'||_filter=='manufacturer'||_filter=='team'||_filter=='price'||_filter=='year'||_filter=='sport'||_filter=='player'){var mobilefilter='#mobile_filters_body .single_mobile_filters_wrapper[data-type="'+_filter+'"] .single_mobile_filters_wrapper_body a[data-value="'+jQuery(this).val()+'"]';if(jQuery(this).prop('checked')){if(_filter=='price'){jQuery('#mobile_filters_body .single_mobile_filters_wrapper[data-type="'+_filter+'"] .single_mobile_filters_wrapper_body a').removeClass('active');}
jQuery(mobilefilter).addClass('active');}else{jQuery(mobilefilter).removeClass('active');}}
SADS.fetchAndRenderFilters();});jQuery('#apply_c_price').off().on('click',function(){var min_price=jQuery('input[name="min_price"]').val();var max_price=jQuery('input[name="max_price"]').val();if(min_price.length<1||max_price.length<1){if(min_price.length<1){jQuery('input[name="min_price"]').addClass('has_error');}else{jQuery('input[name="min_price"]').removeClass('has_error');}
if(max_price.length<1){jQuery('input[name="max_price"]').addClass('has_error');}else{jQuery('input[name="max_price"]').removeClass('has_error');}
return;}else{jQuery('input[name="min_price"]').removeClass('has_error');jQuery('input[name="max_price"]').removeClass('has_error');}
jQuery('#advanced_filters .advanced_filter#filter_price input[type="radio"]').each(function(){jQuery(this).prop('checked',false);});SADS.fetchAndRenderFilters();});jQuery('.single_mobile_filters_wrapper_header p').on('click',function(){jQuery(this).closest('.single_mobile_filters_wrapper_header').toggleClass('active');});jQuery('.single_mobile_filters_wrapper_body a').off().on('click',function(e){e.preventDefault();var _button=jQuery(this);var _filter_wrapper=_button.closest('.single_mobile_filters_wrapper');var _filter=_filter_wrapper.attr('data-type');if(_filter=='price'||_filter=='manufacturer'||_filter=='grade'||_filter=='team'||_filter=='year'||_filter=='sport'||_filter=='player'){var is_removing=false;if(_filter=='team'||_filter=='manufacturer'||_filter=='grade'||_filter=='year'||_filter=='sport'||_filter=='player'){if(_button.hasClass('active')){_button.removeClass('active');is_removing=true;}else{_button.addClass('active');is_removing=false;}}else{_filter_wrapper.find('a').removeClass('active');if(_button.hasClass('active')){_button.removeClass('active');is_removing=true;}else{_button.addClass('active');is_removing=false;}}
if(_filter=='team'||_filter=='manufacturer'||_filter=='grade'||_filter=='year'||_filter=='sport'||_filter=='player'){var desktopholder='#advanced_filters #filter_'+_filter+' .inner input[value="'+_button.attr('data-value')+'"]';if(!is_removing){jQuery(desktopholder).prop('checked',true);}else{jQuery(desktopholder).prop('checked',false);}
jQuery(desktopholder).trigger('change');}
if(_filter=='price'){var desktopholder='#advanced_filters #filter_'+_filter+' .inner input[value="'+_button.attr('data-value')+'"]';jQuery(desktopholder).prop('checked',true);jQuery(desktopholder).trigger('change');}}});jQuery('div#mobile_filters_popup_holder .mobile_filters_header a#mobile_filters_closer,div#mobile_filters_dropshadow,.mobile_filter_button_holder button#mobile_filters_opener').off().on('click',function(e){e.preventDefault();jQuery('body').toggleClass('mobile_filters_active');});jQuery('.sohailms_pagination.ajaxed a').off().on('click',function(e){e.preventDefault();var _targetA=jQuery(this);if(jQuery(this).hasClass('next')){_targetA=jQuery('.sohailms_pagination.ajaxed .page-numbers.current').next('a');}else if(jQuery(this).hasClass('prev')){_targetA=jQuery('.sohailms_pagination.ajaxed .page-numbers.current').prev('a');}
var _targetHref=_targetA.attr('href');var m=_targetHref.match(/([^\?]*)\?_paged=(\d*)/);if(m&&Array.isArray(m)&&m.length>1){var _paged=m[2];sohailms_filter.paged=_paged;SADS.appendURLParams({_paged:_paged});SADS.fetchAndRenderFilters();}else{var _paged=1;sohailms_filter.paged=_paged;SADS.appendURLParams({_paged:_paged});SADS.fetchAndRenderFilters();}});jQuery('div#mobile_filters_footer a').off().on('click',function(e){e.preventDefault();jQuery('div#mobile_filters_popup_holder .mobile_filters_header a#mobile_filters_closer').trigger('click');});jQuery('a.load_more_filters').off().on('click',function(e){e.preventDefault();var _button=jQuery(this);var _wrapper=_button.closest('.advanced_filter');if(_button.hasClass('less')){_button.removeClass('less');_wrapper.find('.for_later_filters').removeClass('less');jQuery(this).closest('.inner').removeClass('less');_button.text('Show More');}else{_button.addClass('less');_wrapper.find('.for_later_filters').addClass('less');jQuery(this).closest('.inner').addClass('less');_button.text('Show Less');}});jQuery('div#mobile_filters_popup_holder .mobile_filters_header .mobile_filters_input_group input#mobile_filters_query').off().on('change input keyup keypress keydown',function(){var _query=jQuery(this).val();if(_query.length<1){jQuery('#mobile_filters_body .single_mobile_filters_wrapper').removeClass('shouldbehidden');return;}
_query=_query.toLowerCase();jQuery('#mobile_filters_body').addClass('searching');jQuery('#mobile_filters_body .single_mobile_filters_wrapper').each(function(){var _type=jQuery(this).attr('data-type');if(_type.indexOf(_query)<0){jQuery(this).addClass('shouldbehidden');}else{jQuery(this).removeClass('shouldbehidden');}});});setTimeout(function(){SADS.initListView();},1000);},initPriceFilter:function(){var holder='#advanced_filters #filter_price .inner';jQuery(holder).html('');var heading='#advanced_filters #filter_price .heading';jQuery(heading).text('Price');var curr_params=SADS.currenURLParems().search;var min_value=max_value='';var price_arr=[];if(curr_params.indexOf('price=')>-1){var rr=new URLSearchParams(SADS.currenURLParems().search);var price_str=rr.get('price');if(price_str.length>0){price_arr=price_str.split('_');}}
for(var key in SADS.priceFilter){if(SADS.priceFilter.hasOwnProperty(key)){var checked='';if(curr_params.indexOf(SADS.priceFilter[key].val)>-1){checked='checked="checked"';min_value=max_value='';price_arr=['',''];}
jQuery(holder).append('<label><input '+checked+' value="'+SADS.priceFilter[key].val+'" type="checkbox" name="filter_price" />'+SADS.priceFilter[key].label+'<span class="checkmark"></span></label>');}}
if(price_arr.length<1){price_arr[0]='';price_arr[1]='';}
jQuery(holder).append('<div class="grouped custom_price"><div class="single_custom_price"><span>$</span><input type="number" name="min_price" value="'+price_arr[0]+'" placeholder="Min" /></div><div class="single_custom_price"><span>$</span><input type="number" value="'+price_arr[1]+'" name="max_price" placeholder="Max" /></div><button id="apply_c_price">Apply</button></div>');},initLoopSlider:function(){jQuery(".lightSlider").addClass("owl-carousel").owlCarousel({items:1,dots:true,nav:true});}}
jQuery(document).ready(function(){if(true){SADS.init();}
setTimeout(function(){SADS.initListView();jQuery(window).on('resize',function(){var _headerHeight=jQuery('#masthead').height();var _subOffTop=jQuery('.subcategs').offset()?.top;var _limit=_subOffTop-_headerHeight;if(jQuery(window).width()<768){jQuery(window).on('scroll',function(){if(jQuery(this).scrollTop()>216){jQuery('.subcategs').addClass('show_sticky');}else{jQuery('.subcategs').removeClass('show_sticky');}});}});},900);});jQuery(document).on("click",function(e){if(!jQuery(event.target).closest(".searchform").length){jQuery('body').removeClass('autocomplete_rendered');}});jQuery('input#s').on('focus',function(){if(jQuery('input#s').val().trim().length>0&&jQuery('ul#autofill-results-holder li').length>0){jQuery('body').addClass('autocomplete_rendered');}else{jQuery('body').removeClass('autocomplete_rendered');}});setTimeout(function(){jQuery('#shift_to_register').off().on('click',function(e){e.preventDefault();jQuery('.custom_error_holder').html('');jQuery('.new_customer_login_page .left_side .account-login-inner').hide();jQuery('.new_customer_login_page .left_side .account-register-inner').show();jQuery('.account-password-reset-inner').hide();const url=new URL(window.location.href);url.searchParams.set('formtype','register');window.history.replaceState(null,null,url);});jQuery('#shift_to_login').off().on('click',function(e){e.preventDefault();jQuery('.custom_error_holder').html('');jQuery('.new_customer_login_page .left_side .account-login-inner').show();jQuery('.new_customer_login_page .left_side .account-register-inner').hide();jQuery('.account-password-reset-inner').hide();const url=new URL(window.location.href);url.searchParams.set('formtype','login');window.history.replaceState(null,null,url);});jQuery('.new_customer_login_page form p.woocommerce-LostPassword.lost_password').off().on('click',function(e){e.preventDefault();jQuery('.custom_error_holder').html('');jQuery('.new_customer_login_page .left_side .account-login-inner').hide();jQuery('.new_customer_login_page .left_side .account-register-inner').hide();jQuery('.account-password-reset-inner').show();const url=new URL(window.location.href);url.searchParams.set('formtype','lostpass');window.history.replaceState(null,null,url);});jQuery('#shift_to_login_again').off().on('click',function(e){e.preventDefault();jQuery('.custom_error_holder').html('');jQuery('.new_customer_login_page .left_side .account-login-inner').show();jQuery('.new_customer_login_page .left_side .account-register-inner').hide();jQuery('.account-password-reset-inner').hide();const url=new URL(window.location.href);url.searchParams.set('formtype','login');window.history.replaceState(null,null,url);});jQuery('#custom_product_sorter_sorter').off().on('change',function(){var _val=jQuery(this).val();if(_val.length<1){return '';}
jQuery(jQuery('div#advanced_filters label input')[0]).trigger('change');});},1000);setTimeout(function(){if(jQuery('.woocommerce-error.message-wrapper').length>0){jQuery('.custom_error_holder').html(jQuery('.woocommerce-error.message-wrapper').html());}},500);setTimeout(function(){if(banner_config){var showbanner=false;var txt='';var btntxt='';var btncolor='';var btntxtcolor='';var btnlink='';var style='';var output='';var body_id=parseInt(jQuery("body").attr("data-body_id"));if(banner_config.banner_one_on_off=='yes'){showbanner=true;if(banner_config.pages_one.indexOf(body_id+'')<0){showbanner=false;}
style='style="background:'+banner_config.banner_data.banner_one.btncolor+';color:'+banner_config.banner_data.banner_one.btntextcolor+';"';txt=banner_config.banner_data.banner_one.text;}
if(showbanner){if(!jQuery('body').hasClass('home')&&jQuery('#top_banner_area')){jQuery('#top_banner_area').append('<p>'+txt+'</p>');jQuery('#top_banner_area').css({backgroundColor:banner_config.banner_data.banner_one.btncolor,color:banner_config.banner_data.banner_one.btntextcolor});}else if(jQuery('body').hasClass('home')){jQuery('body').addClass('home_banner_enabled');jQuery('#home_page_banner > .elementor-widget-container').html('').append('<p '+style+'>'+txt+'</p>');}}}},1200);jQuery('document').ready(function(){console.log('laded');jQuery('.new_design_alert,.alert_flipbox_inner .footer a.cancel').off().on('click',function(e){e.preventDefault();var _this=jQuery(this);var _parent=_this.closest('.alert_flipbox_wrapper');_parent.find('input[type="checkbox"]').each(function(){var _val=jQuery(this).attr('data-original_val');if(_val=='active'){jQuery(this).prop('checked',true);}else{jQuery(this).prop('checked',false);}});var _confirm=_this.prev('a.confirm');_confirm.attr('data-id',_confirm.attr('data-org_id'));jQuery(this).closest('.dsdadddd.product-small.box').toggleClass('flipped').removeClass('listview');});jQuery('body.logged-in .dsdadddd.product-small.box .alert_flipbox_wrapper .alert_flipbox_inner .footer a.confirm').off().on('click',function(e){e.preventDefault();var _this=jQuery(this);var _parent=_this.closest('.alert_flipbox_wrapper');var _id=parseInt(_this.attr('data-id'));var _variation_added=_parent.find('input[value="variation_added"]').is(':checked');var _variation_out_of_stock=_parent.find('input[value="variation_out_of_stock"]').is(':checked');var _price_change=_parent.find('input[value="price_change"]').is(':checked');var _item_unavailable=_parent.find('input[value="item_unavailable"]').is(':checked');var _item_available=_parent.find('input[value="item_available"]').is(':checked');var _data={variation_added:_variation_added,variation_out_of_stock:_variation_out_of_stock,price_change:_price_change,item_available:_item_available,item_unavailable:_item_unavailable,id:_id,action:'sohailms_set_notification_alert',};if(_parent.closest('.dsdadddd.product-small.box').hasClass('listview')){_data.ptype='variation';}
jQuery.ajax({url:sohailms_filter.ajaxurl,type:'POST',data:_data,beforeSend:function(){_parent.addClass('sending_data');},success:function(res){_parent.removeClass('sending_data');console.log(res);if(res.success&&res.data.saved_data){if(_parent.closest('.dsdadddd.product-small.box').hasClass('listview')){jQuery('a[data-id="'+_id+'"]').attr('data-settings',JSON.stringify(res.data.saved_data));if(res.data.saved_data.item_unavailable_var=='active'||res.data.saved_data.item_available_var=='active'){jQuery('a[data-id="'+_id+'"]').addClass('filled');}else{jQuery('a[data-id="'+_id+'"]').removeClass('filled');}}
_parent.find('input[value="price_change"]').attr('data-original_val',res.data.saved_data.price_change);_parent.find('input[value="variation_added"]').attr('data-original_val',res.data.saved_data.variation_added);_parent.find('input[value="variation_out_of_stock"]').attr('data-original_val',res.data.saved_data.variation_out_of_stock);if(res.data.saved_data.price_change=='active'||res.data.saved_data.variation_added=='active'||res.data.saved_data.variation_out_of_stock=='active'){_parent.closest('.product-small.col').find('.new_design_alert').addClass('filled');_parent.closest('.product-small.col').find('.alert_flipbox_wrapper h3 span:last-child').addClass('filled');}else{_parent.closest('.product-small.col').find('.new_design_alert').removeClass('filled');_parent.closest('.product-small.col').find('.alert_flipbox_wrapper h3 span:last-child').removeClass('filled');}
_parent.closest('.dsdadddd.product-small.box').removeClass('flipped');}}});});jQuery('.fornew_listview.newactions a.single_var_alert').off().on('click',function(e){e.preventDefault();var _this=jQuery(this);var _id=_this.attr('data-id');var _settings=JSON.parse(_this.attr('data-settings'));var _parent=_this.closest('.dsdadddd.product-small.box');var _settings=JSON.parse(_this.attr('data-settings'));if(_settings.item_unavailable_var&&_settings.item_unavailable_var=='active'){_parent.find('input[value="item_unavailable"]').prop('checked',true);}else{_parent.find('input[value="item_unavailable"]').prop('checked',false);}
if(_settings.item_available_var&&_settings.item_available_var=='active'){_parent.find('input[value="item_available"]').prop('checked',true);}else{_parent.find('input[value="item_available"]').prop('checked',false);}
_parent.find('.footer a.confirm').attr('data-id',_id);_parent.addClass('flipped listview');});});})(jQuery);